sonar.verbose=true
sonar.organization=prasann01-key
sonar.projectKey=prasann01-key_prasann-project
sonar.projectName=prasann-project
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
